
version: '3'


networks:
  dnsmasq_net:
    driver: bridge


services:

  dnsmasq:
    container_name: dnsmasq
    image: nteptartifact:5014/webproc/dnsmasq:0.4.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    ports:
      - "5380:8080"
      - "53:53"
    environment:
      - HTTP_USER=foo
      - HTTP_PASS=bar
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    restart: always
    healthcheck:
      test: ["CMD-SHELL", " echo Executing: curl -u $$HTTP_USER:$$HTTP_PASS --fail http://localhost:8080  && curl -u $$HTTP_USER:$$HTTP_PASS --fail http://localhost:8080 "]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - dnsmasq_net
      
      


